// ============================================================
// tpp.com — Sample Data
// ============================================================

// --- Deals ---
const deals = [
  {
    id: 1,
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Quart",
    store: "Amazon",
    storeIcon: "amazon",
    category: "kitchen",
    originalPrice: 99.99,
    dealPrice: 49.99,
    discount: 50,
    rating: 4.7,
    reviewCount: 52341,
    image: "https://picsum.photos/seed/instantpot/600/400",
    description: "Best-selling pressure cooker — 7 functions in one appliance. Cooks up to 70% faster.",
    url: "#",
    postedAt: "2026-07-27T08:30:00",
    expiresAt: "2026-07-30",
    featured: true,
    hot: true
  },
  {
    id: 2,
    title: "Samsung 65\" Class OLED 4K Smart TV (2026 Model)",
    store: "Best Buy",
    storeIcon: "bestbuy",
    category: "electronics",
    originalPrice: 1799.99,
    dealPrice: 1299.99,
    discount: 28,
    rating: 4.8,
    reviewCount: 1823,
    image: "https://picsum.photos/seed/samsungtv/600/400",
    description: "Stunning OLED picture quality with AI-powered 4K upscaling. Limited-time doorbuster.",
    url: "#",
    postedAt: "2026-07-27T09:15:00",
    expiresAt: "2026-07-28",
    featured: true,
    hot: true
  },
  {
    id: 3,
    title: "LEGO Classic Large Creative Brick Box 790 Pieces",
    store: "Walmart",
    storeIcon: "walmart",
    category: "toys",
    originalPrice: 49.99,
    dealPrice: 29.99,
    discount: 40,
    rating: 4.9,
    reviewCount: 28456,
    image: "https://picsum.photos/seed/lego/600/400",
    description: "Perfect creative building set for kids ages 4-99. Includes 790 pieces in 33 colors.",
    url: "#",
    postedAt: "2026-07-27T07:00:00",
    expiresAt: "2026-07-31",
    featured: false,
    hot: true
  },
  {
    id: 4,
    title: "Olay Regenerist Retinol 24 Night Moisturizer, 1.7 oz",
    store: "Target",
    storeIcon: "target",
    category: "beauty",
    originalPrice: 38.99,
    dealPrice: 22.49,
    discount: 42,
    rating: 4.5,
    reviewCount: 12450,
    image: "https://picsum.photos/seed/olay/600/400",
    description: "Anti-aging night cream with Retinol & Vitamin B3. Smooths fine lines overnight.",
    url: "#",
    postedAt: "2026-07-27T06:45:00",
    expiresAt: "2026-08-03",
    featured: false,
    hot: false
  },
  {
    id: 5,
    title: "Nike Air Max 270 Women's Running Shoes",
    store: "Nike",
    storeIcon: "nike",
    category: "fashion",
    originalPrice: 150.00,
    dealPrice: 89.99,
    discount: 40,
    rating: 4.6,
    reviewCount: 8972,
    image: "https://picsum.photos/seed/nikeshoes/600/400",
    description: "Lifestyle sneaker with the largest Air unit yet. Multiple colorways available.",
    url: "#",
    postedAt: "2026-07-26T14:20:00",
    expiresAt: "2026-07-29",
    featured: false,
    hot: true
  },
  {
    id: 6,
    title: "iRobot Roomba j7+ Self-Emptying Robot Vacuum",
    store: "Amazon",
    storeIcon: "amazon",
    category: "home",
    originalPrice: 799.99,
    dealPrice: 499.99,
    discount: 38,
    rating: 4.4,
    reviewCount: 6731,
    image: "https://picsum.photos/seed/roomba/600/400",
    description: "Self-emptying robot vacuum with precision obstacle avoidance. Empties itself for 60 days.",
    url: "#",
    postedAt: "2026-07-26T11:00:00",
    expiresAt: "2026-08-01",
    featured: true,
    hot: false
  },
  {
    id: 7,
    title: "KitchenAid Artisan Series 5 Qt Stand Mixer",
    store: "Kohl's",
    storeIcon: "kohls",
    category: "kitchen",
    originalPrice: 449.99,
    dealPrice: 299.99,
    discount: 33,
    rating: 4.8,
    reviewCount: 15620,
    image: "https://picsum.photos/seed/kitchenaid/600/400",
    description: "Iconic stand mixer in 10+ colors. Includes flat beater, dough hook, and wire whip.",
    url: "#",
    postedAt: "2026-07-26T09:30:00",
    expiresAt: "2026-08-05",
    featured: false,
    hot: true
  },
  {
    id: 8,
    title: "Apple AirPods Pro (3rd Generation) with USB-C",
    store: "Best Buy",
    storeIcon: "bestbuy",
    category: "electronics",
    originalPrice: 249.99,
    dealPrice: 189.99,
    discount: 24,
    rating: 4.7,
    reviewCount: 34120,
    image: "https://picsum.photos/seed/airpods/600/400",
    description: "Adaptive Audio. Active Noise Cancellation. Personalized Spatial Audio.",
    url: "#",
    postedAt: "2026-07-26T08:00:00",
    expiresAt: "2026-07-28",
    featured: false,
    hot: false
  },
  {
    id: 9,
    title: "Purina ONE Natural Dry Dog Food, 31.1 lb Bag",
    store: "Chewy",
    storeIcon: "chewy",
    category: "pets",
    originalPrice: 48.99,
    dealPrice: 34.99,
    discount: 29,
    rating: 4.6,
    reviewCount: 18920,
    image: "https://picsum.photos/seed/dogfood/600/400",
    description: "Real chicken is the #1 ingredient. Veterinarian-recommended formula for adult dogs.",
    url: "#",
    postedAt: "2026-07-25T16:00:00",
    expiresAt: "2026-08-02",
    featured: false,
    hot: false
  },
  {
    id: 10,
    title: "Cuisinart 14-Cup Food Processor, Stainless Steel",
    store: "Amazon",
    storeIcon: "amazon",
    category: "kitchen",
    originalPrice: 249.99,
    dealPrice: 149.99,
    discount: 40,
    rating: 4.5,
    reviewCount: 7823,
    image: "https://picsum.photos/seed/foodprocessor/600/400",
    description: "Powerful 720-watt motor. Extra-large 14-cup capacity with BPA-free Tritan work bowl.",
    url: "#",
    postedAt: "2026-07-25T13:30:00",
    expiresAt: "2026-07-31",
    featured: false,
    hot: false
  },
  {
    id: 11,
    title: "BISSELL Little Green Multi-Purpose Portable Carpet Cleaner",
    store: "Target",
    storeIcon: "target",
    category: "home",
    originalPrice: 129.99,
    dealPrice: 84.99,
    discount: 35,
    rating: 4.6,
    reviewCount: 12450,
    image: "https://picsum.photos/seed/bissell/600/400",
    description: "Portable deep cleaner for carpet, upholstery, auto interiors, and stairs.",
    url: "#",
    postedAt: "2026-07-25T10:00:00",
    expiresAt: "2026-07-29",
    featured: false,
    hot: false
  },
  {
    id: 12,
    title: "Anthropologie Gleaming Primrose Mirror — 40\" Diameter",
    store: "Anthropologie",
    storeIcon: "anthropologie",
    category: "home",
    originalPrice: 598.00,
    dealPrice: 349.00,
    discount: 42,
    rating: 4.4,
    reviewCount: 4521,
    image: "https://picsum.photos/seed/mirror/600/400",
    description: "Stunning statement mirror with gleaming gold finish. Perfect above a mantel or vanity.",
    url: "#",
    postedAt: "2026-07-24T15:45:00",
    expiresAt: "2026-08-05",
    featured: false,
    hot: false
  },
  {
    id: 13,
    title: "Columbia Women's Arcadia II Waterproof Rain Jacket",
    store: "Columbia",
    storeIcon: "columbia",
    category: "fashion",
    originalPrice: 79.99,
    dealPrice: 39.99,
    discount: 50,
    rating: 4.5,
    reviewCount: 9832,
    image: "https://picsum.photos/seed/rainjacket/600/400",
    description: "Lightweight, packable waterproof breathable rain jacket. Available in 15+ colors.",
    url: "#",
    postedAt: "2026-07-24T12:00:00",
    expiresAt: "2026-07-30",
    featured: false,
    hot: false
  },
  {
    id: 14,
    title: "Dyson V15 Detect Cordless Vacuum Cleaner",
    store: "Amazon",
    storeIcon: "amazon",
    category: "home",
    originalPrice: 749.99,
    dealPrice: 549.99,
    discount: 27,
    rating: 4.7,
    reviewCount: 15340,
    image: "https://picsum.photos/seed/dyson/600/400",
    description: "Laser reveals microscopic dust. Piezo sensor counts particles. 60-minute runtime.",
    url: "#",
    postedAt: "2026-07-24T09:00:00",
    expiresAt: "2026-07-28",
    featured: false,
    hot: true
  },
  {
    id: 15,
    title: "Crayola Inspiration Art Case Coloring Set, 140 Pieces",
    store: "Walmart",
    storeIcon: "walmart",
    category: "toys",
    originalPrice: 29.99,
    dealPrice: 14.99,
    discount: 50,
    rating: 4.8,
    reviewCount: 23100,
    image: "https://picsum.photos/seed/crayola/600/400",
    description: "All-in-one portable art studio with crayons, colored pencils, markers, and paper.",
    url: "#",
    postedAt: "2026-07-23T16:30:00",
    expiresAt: "2026-08-01",
    featured: false,
    hot: true
  },
  {
    id: 16,
    title: "Starbucks French Roast Dark Roast Ground Coffee, 28 oz",
    store: "Costco",
    storeIcon: "costco",
    category: "food",
    originalPrice: 21.99,
    dealPrice: 14.99,
    discount: 32,
    rating: 4.7,
    reviewCount: 8740,
    image: "https://picsum.photos/seed/starbucks/600/400",
    description: "Intensely smoky and bold dark roast. 2-pack bundle deal at Costco.",
    url: "#",
    postedAt: "2026-07-23T14:00:00",
    expiresAt: "2026-08-03",
    featured: false,
    hot: false
  },
  {
    id: 17,
    title: "Revlon One-Step Volumizer PLUS 2.0 Hair Dryer & Styler",
    store: "Ulta",
    storeIcon: "ulta",
    category: "beauty",
    originalPrice: 69.99,
    dealPrice: 39.99,
    discount: 43,
    rating: 4.6,
    reviewCount: 45620,
    image: "https://picsum.photos/seed/revlon/600/400",
    description: "The viral oval brush dryer. Salon-quality blowout in half the time.",
    url: "#",
    postedAt: "2026-07-23T10:30:00",
    expiresAt: "2026-07-30",
    featured: false,
    hot: true
  },
  {
    id: 18,
    title: "Graco Extend2Fit Convertible Car Seat, 3-in-1",
    store: "BuyBuy Baby",
    storeIcon: "buybuybaby",
    category: "baby",
    originalPrice: 229.99,
    dealPrice: 159.99,
    discount: 30,
    rating: 4.7,
    reviewCount: 12340,
    image: "https://picsum.photos/seed/carseat/600/400",
    description: "Grows with your child from 4-65 lbs. 3-in-1 convertible design. Top safety ratings.",
    url: "#",
    postedAt: "2026-07-23T08:00:00",
    expiresAt: "2026-08-06",
    featured: false,
    hot: false
  },
  {
    id: 19,
    title: "Google Nest Learning Thermostat (4th Gen)",
    store: "Best Buy",
    storeIcon: "bestbuy",
    category: "electronics",
    originalPrice: 279.99,
    dealPrice: 219.99,
    discount: 21,
    rating: 4.5,
    reviewCount: 6780,
    image: "https://picsum.photos/seed/nest/600/400",
    description: "Auto-schedule programming. Energy-saving Eco mode. Control from anywhere.",
    url: "#",
    postedAt: "2026-07-22T15:00:00",
    expiresAt: "2026-07-29",
    featured: false,
    hot: false
  },
  {
    id: 20,
    title: "Patagonia Better Sweater Fleece Jacket — Men's",
    store: "REI",
    storeIcon: "rei",
    category: "fashion",
    originalPrice: 139.00,
    dealPrice: 79.00,
    discount: 43,
    rating: 4.8,
    reviewCount: 5430,
    image: "https://picsum.photos/seed/patagonia/600/400",
    description: "Fair Trade Certified sewn. Warm fleece knit with sweater-knit face. Durable and cozy.",
    url: "#",
    postedAt: "2026-07-22T12:00:00",
    expiresAt: "2026-08-01",
    featured: false,
    hot: false
  },
  {
    id: 21,
    title: "Ninja Creami Deluxe Ice Cream Maker, 11-in-1",
    store: "Amazon",
    storeIcon: "amazon",
    category: "kitchen",
    originalPrice: 249.99,
    dealPrice: 179.99,
    discount: 28,
    rating: 4.4,
    reviewCount: 8910,
    image: "https://picsum.photos/seed/creami/600/400",
    description: "Make ice cream, sorbet, gelato, milkshakes, smoothie bowls & more at home.",
    url: "#",
    postedAt: "2026-07-22T09:30:00",
    expiresAt: "2026-08-04",
    featured: false,
    hot: false
  },
  {
    id: 22,
    title: "Nintendo Switch OLED Model — Mario Kart 8 Bundle",
    store: "GameStop",
    storeIcon: "gamestop",
    category: "electronics",
    originalPrice: 349.99,
    dealPrice: 299.99,
    discount: 14,
    rating: 4.9,
    reviewCount: 12400,
    image: "https://picsum.photos/seed/switch/600/400",
    description: "Includes console, dock, Joy-Cons, and Mario Kart 8 Deluxe digital download.",
    url: "#",
    postedAt: "2026-07-21T18:00:00",
    expiresAt: "2026-07-28",
    featured: false,
    hot: true
  },
  {
    id: 23,
    title: "lululemon Align High-Rise Leggings 28\"",
    store: "lululemon",
    storeIcon: "lululemon",
    category: "fashion",
    originalPrice: 98.00,
    dealPrice: 69.00,
    discount: 30,
    rating: 4.7,
    reviewCount: 18750,
    image: "https://picsum.photos/seed/leggings/600/400",
    description: "Buttery-soft Nulu fabric. Weightless, breathable feel. Perfect for yoga and everyday.",
    url: "#",
    postedAt: "2026-07-21T14:00:00",
    expiresAt: "2026-07-31",
    featured: false,
    hot: false
  },
  {
    id: 24,
    title: "Vitamix E310 Explorian Blender, Professional-Grade",
    store: "Costco",
    storeIcon: "costco",
    category: "kitchen",
    originalPrice: 379.99,
    dealPrice: 279.99,
    discount: 26,
    rating: 4.7,
    reviewCount: 9850,
    image: "https://picsum.photos/seed/vitamix/600/400",
    description: "Variable speed control. Aircraft-grade stainless steel blades. 64 oz container.",
    url: "#",
    postedAt: "2026-07-21T10:00:00",
    expiresAt: "2026-08-07",
    featured: false,
    hot: false
  }
];

// --- Recipes ---
const recipes = [
  {
    id: 1,
    title: "One-Pot Creamy Tuscan Chicken Pasta",
    category: "dinner",
    image: "https://picsum.photos/seed/recipe1/600/400",
    cookTime: "30 min",
    difficulty: "Easy",
    rating: 4.8,
    reviewCount: 234,
    description: "Creamy sundried tomato pasta with tender chicken and spinach — all in one pot!",
    url: "#"
  },
  {
    id: 2,
    title: "Air Fryer Crispy Parmesan Brussels Sprouts",
    category: "sides",
    image: "https://picsum.photos/seed/recipe2/600/400",
    cookTime: "15 min",
    difficulty: "Easy",
    rating: 4.6,
    reviewCount: 187,
    description: "Crispy on the outside, tender on the inside. Even the kids will ask for seconds!",
    url: "#"
  },
  {
    id: 3,
    title: "Slow Cooker Beef Barbacoa Tacos",
    category: "dinner",
    image: "https://picsum.photos/seed/recipe3/600/400",
    cookTime: "8 hrs",
    difficulty: "Easy",
    rating: 4.9,
    reviewCount: 312,
    description: "Set-it-and-forget-it shredded beef with chipotle, lime, and cilantro.",
    url: "#"
  },
  {
    id: 4,
    title: "No-Bake Oreo Cheesecake Parfaits",
    category: "dessert",
    image: "https://picsum.photos/seed/recipe4/600/400",
    cookTime: "20 min",
    difficulty: "Easy",
    rating: 4.7,
    reviewCount: 156,
    description: "Creamy, crunchy, chocolatey layered dessert ready in 20 minutes flat.",
    url: "#"
  },
  {
    id: 5,
    title: "Copycat Starbucks Pumpkin Cream Cold Brew",
    category: "drinks",
    image: "https://picsum.photos/seed/recipe5/600/400",
    cookTime: "10 min",
    difficulty: "Easy",
    rating: 4.5,
    reviewCount: 421,
    description: "Save $6 per drink! Rich pumpkin sweet cream over smooth cold brew at home.",
    url: "#"
  },
  {
    id: 6,
    title: "Sheet Pan Lemon Herb Salmon & Asparagus",
    category: "dinner",
    image: "https://picsum.photos/seed/recipe6/600/400",
    cookTime: "25 min",
    difficulty: "Easy",
    rating: 4.8,
    reviewCount: 278,
    description: "Healthy, gorgeous, and SO easy. Just one pan + 5 ingredients = dinner is done.",
    url: "#"
  }
];

// --- DIY Projects ---
const diyProjects = [
  {
    id: 1,
    title: "DIY Floating Picture Frame Gallery Wall",
    category: "home-decor",
    image: "https://picsum.photos/seed/diy1/600/400",
    difficulty: "Easy",
    time: "2 hours",
    cost: "$30",
    description: "Create a stunning gallery wall with dollar-store frames and gold spray paint.",
    url: "#"
  },
  {
    id: 2,
    title: "No-Sew Fleece Tie Blanket — Perfect Gift!",
    category: "crafts",
    image: "https://picsum.photos/seed/diy2/600/400",
    difficulty: "Easy",
    time: "1 hour",
    cost: "$15",
    description: "The coziest DIY gift ever. No sewing machine needed — just two fleece layers and scissors.",
    url: "#"
  },
  {
    id: 3,
    title: "IKEA Kallax Hack: Built-In Window Bench with Storage",
    category: "furniture",
    image: "https://picsum.photos/seed/diy3/600/400",
    difficulty: "Medium",
    time: "4 hours",
    cost: "$120",
    description: "Transform basic IKEA shelves into a beautiful window seat with hidden storage.",
    url: "#"
  },
  {
    id: 4,
    title: "Mason Jar Herb Garden for Your Kitchen Windowsill",
    category: "garden",
    image: "https://picsum.photos/seed/diy4/600/400",
    difficulty: "Easy",
    time: "30 min",
    cost: "$12",
    description: "Fresh herbs year-round! Paint-dipped mason jars with chalkboard labels.",
    url: "#"
  },
  {
    id: 5,
    title: "Kids' Artwork Display Wall with IKEA Curtain Rods",
    category: "kids",
    image: "https://picsum.photos/seed/diy5/600/400",
    difficulty: "Easy",
    time: "45 min",
    cost: "$25",
    description: "Finally organize (and proudly show off) the masterpieces with easy-clip hanging.",
    url: "#"
  },
  {
    id: 6,
    title: "DIY Outdoor Pallet Sectional Sofa",
    category: "furniture",
    image: "https://picsum.photos/seed/diy6/600/400",
    difficulty: "Medium",
    time: "6 hours",
    cost: "$80",
    description: "Build a gorgeous L-shaped outdoor sofa from free pallets. Wayfair dupe for under $100!",
    url: "#"
  }
];

// --- Tips ---
const tips = [
  {
    id: 1,
    title: "The Best Times to Book Flights for the Cheapest Fares in 2026",
    category: "travel",
    image: "https://picsum.photos/seed/tip1/600/400",
    description: "Data shows Tuesday afternoons are no longer the sweet spot. Here's when to book now.",
    url: "#"
  },
  {
    id: 2,
    title: "How to Stack Coupons at Target: The Ultimate Guide for 2026",
    category: "saving",
    image: "https://picsum.photos/seed/tip2/600/400",
    description: "Manufacturer + store + Cartwheel + RedCard = savings you won't believe. We show you how.",
    url: "#"
  },
  {
    id: 3,
    title: "10 Things You Should Always Buy at Dollar Tree (and 5 to Skip)",
    category: "saving",
    image: "https://picsum.photos/seed/tip3/600/400",
    description: "Some dollar-store finds are incredible deals. Others are a waste. Here's the definitive list.",
    url: "#"
  },
  {
    id: 4,
    title: "How to Organize Your Pantry Like a Pro (on a Budget!)",
    category: "home",
    image: "https://picsum.photos/seed/tip4/600/400",
    description: "Clear containers, labeled bins, and smart zones — all from Dollar Tree and Amazon deals.",
    url: "#"
  },
  {
    id: 5,
    title: "The Secret to Getting Hotel Upgrades Without Paying Extra",
    category: "travel",
    image: "https://picsum.photos/seed/tip5/600/400",
    description: "Front desk agents share what actually works: timing, tone, and one magic question.",
    url: "#"
  },
  {
    id: 6,
    title: "Meal Planning on $75/Week: How One Mom Feeds a Family of 5",
    category: "food",
    image: "https://picsum.photos/seed/tip6/600/400",
    description: "Complete weekly meal plan with grocery list, recipes, and exactly how much it all costs.",
    url: "#"
  }
];

// --- Stores ---
const stores = [
  { id: 1, name: "Amazon", icon: "amazon", dealCount: 1247, description: "The largest online retailer with daily Lightning Deals and Prime-exclusive discounts.", url: "#" },
  { id: 2, name: "Walmart", icon: "walmart", dealCount: 856, description: "Everyday low prices meet Rollback deals. Free pickup on online orders.", url: "#" },
  { id: 3, name: "Target", icon: "target", dealCount: 632, description: "Stack Cartwheel offers, Target Circle rewards, and RedCard 5% for maximum savings.", url: "#" },
  { id: 4, name: "Best Buy", icon: "bestbuy", dealCount: 489, description: "Electronics deals with price match guarantee. Open-box discounts up to 40% off.", url: "#" },
  { id: 5, name: "Costco", icon: "costco", dealCount: 321, description: "Warehouse bulk savings. Members-only prices on everything from groceries to electronics.", url: "#" },
  { id: 6, name: "Walgreens", icon: "walgreens", dealCount: 278, description: "Weekly ad deals, Balance Rewards points, and digital coupon clipping.", url: "#" },
  { id: 7, name: "CVS", icon: "cvs", dealCount: 245, description: "ExtraCare Rewards + ExtraBucks = free stuff. Learn to play the CVS coupon game.", url: "#" },
  { id: 8, name: "Kohl's", icon: "kohls", dealCount: 198, description: "Kohl's Cash earning periods + stackable coupons = 60%+ off regular prices.", url: "#" }
];

// --- Coupons ---
const coupons = [
  { id: 1, store: "Target", title: "$5 off $25+ Home Essentials Purchase", code: "HOME5", discount: "$5 off", category: "home", expiresAt: "2026-08-15", description: "Valid on cleaning supplies, storage, and home decor. In-store and online.", url: "#" },
  { id: 2, store: "Bed Bath & Beyond", title: "20% Off One Single Item", code: "SAVE20", discount: "20% off", category: "home", expiresAt: "2026-08-10", description: "Classic coupon — valid on regular-priced merchandise. Some exclusions apply.", url: "#" },
  { id: 3, store: "JOANN", title: "40% Off One Regular Price Item + Free Shipping $50+", code: "CRAFT40", discount: "40% off", category: "crafts", expiresAt: "2026-08-05", description: "Stack with sale prices for fabric, yarn, and craft supplies.", url: "#" },
  { id: 4, store: "Hobby Lobby", title: "40% Off Any One Regular Price Item", code: "HOBBY40", discount: "40% off", category: "crafts", expiresAt: "2026-08-03", description: "Always-available coupon. Use for big-ticket craft items and home decor.", url: "#" },
  { id: 5, store: "Old Navy", title: "30% Off Your Entire Purchase + Free Shipping", code: "ONSTYLE", discount: "30% off", category: "fashion", expiresAt: "2026-08-08", description: "Valid on regular and sale items. Includes free shipping — no minimum.", url: "#" },
  { id: 6, store: "Michaels", title: "25% Off Entire Purchase Including Sale Items", code: "CREATE25", discount: "25% off", category: "crafts", expiresAt: "2026-08-12", description: "Rare whole-purchase coupon! Includes Cricut, Silhouette, and storage.", url: "#" },
  { id: 7, store: "DSW", title: "$10 Off $49+ + Free Shipping", code: "SHOES10", discount: "$10 off", category: "fashion", expiresAt: "2026-08-20", description: "Valid on all footwear and accessories. VIP members earn double points.", url: "#" },
  { id: 8, store: "PetSmart", title: "15% Off Curbside Pickup Orders $50+", code: "PETS15", discount: "15% off", category: "pets", expiresAt: "2026-08-18", description: "Online only. Choose in-store pickup at checkout to apply.", url: "#" },
  { id: 9, store: "Lowe's", title: "$20 Off $100+ Paint & Painting Supplies", code: "PAINT20", discount: "$20 off", category: "home", expiresAt: "2026-08-25", description: "Perfect for summer refresh projects. Includes spray paint and brushes.", url: "#" },
  { id: 10, store: "Ulta", title: "$3.50 Off $15+ + Free 4-Piece Gift with $25+", code: "ULTA350", discount: "$3.50 off", category: "beauty", expiresAt: "2026-08-14", description: "Stack with Ulta Beauty Rewards points for extra savings.", url: "#" }
];

// --- Categories ---
const categories = [
  { slug: "all", name: "All Deals", icon: "🏷️" },
  { slug: "electronics", name: "Electronics", icon: "📱" },
  { slug: "kitchen", name: "Kitchen & Dining", icon: "🍳" },
  { slug: "home", name: "Home & Garden", icon: "🏠" },
  { slug: "fashion", name: "Fashion", icon: "👗" },
  { slug: "beauty", name: "Beauty", icon: "💄" },
  { slug: "toys", name: "Toys & Games", icon: "🧸" },
  { slug: "baby", name: "Baby & Kids", icon: "🍼" },
  { slug: "pets", name: "Pets", icon: "🐾" },
  { slug: "food", name: "Food & Grocery", icon: "🛒" }
];
